default_target: all
.PHONY: all ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex14 ex15 ex16 ex17 ex18

CXXFLAGS = -lm -std=c99 -I./

all: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex14 ex15 ex16 ex17 ex18

ex1:
	@gcc ex1.c ${CXXFLAGS}  -o ex1.unx

ex2:
	@gcc ex2.c  ${CXXFLAGS} -o ex2.unx

ex3:
	@gcc ex3.c ${CXXFLAGS}  -o ex3.unx

ex4:
	@gcc ex4.c ${CXXFLAGS}  -o ex4.unx
ex5:
	@gcc ex5.c ${CXXFLAGS}  -o ex5.unx
ex6:
	@gcc ex6.c ${CXXFLAGS}  -o ex6.unx
ex7:
	@gcc ex7.c ${CXXFLAGS}  -o ex7.unx
ex8:
	@gcc ex8.c ${CXXFLAGS}  -o ex8.unx
ex14:
	@gcc ex14.c ${CXXFLAGS}  -o ex14.unx
ex15:
	@gcc ex15.c ${CXXFLAGS}  -o ex15.unx
ex16:
	@gcc ex16.c ${CXXFLAGS}  -o ex16.unx
ex17:
	@gcc ex17.c ${CXXFLAGS}  -o ex17.unx

ex18:
	@gcc ex18.c ${CXXFLAGS}  -o ex18.unx	
